const config = window.KON_BOARD_CONFIG || {};
const configured = Boolean(config.supabaseUrl && config.supabaseAnonKey);
const app = document.querySelector('#app');
const loginButton = document.querySelector('#login-button');
const navNew = document.querySelector('#nav-new');
const demoThreads = [
  {id:'demo-1',title:'KON BOARDを作りました！',category:'雑談',author:'kon',created_at:'2026-08-21T00:00:00Z',content:'新しい掲示板の初期版です。どんな機能が欲しい？',comment_count:3},
  {id:'demo-2',title:'おすすめのプログラミング言語',category:'プログラミング',author:'guest',created_at:'2026-08-20T12:00:00Z',content:'初心者におすすめの言語を教えてください。',comment_count:5}
];
let supabase = null;
if (configured) {
  const { createClient } = await import('https://esm.sh/@supabase/supabase-js@2');
  supabase = createClient(config.supabaseUrl, config.supabaseAnonKey, { auth: { persistSession: true, autoRefreshToken: true, detectSessionInUrl: true } });
}
function escapeHtml(value=''){return String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));}
function formatDate(value){return new Intl.DateTimeFormat('ja-JP',{dateStyle:'medium'}).format(new Date(value));}
async function currentUser(){if(!supabase)return null;const {data:{user}}=await supabase.auth.getUser();return user;}
async function requireAuth(){const user=await currentUser();if(user)return user;location.hash='/login';return null;}
function updateAuthUI(session){const signedIn=Boolean(session);loginButton.textContent=signedIn?'ログアウト':'GitHubでログイン';if(navNew)navNew.classList.toggle('protected-nav',!signedIn);}
async function renderHome(){app.replaceChildren(document.querySelector('#home-template').content.cloneNode(true));const list=app.querySelector('#thread-list');const search=app.querySelector('#search-input');const filter=app.querySelector('#category-filter');const draw=async()=>{let rows=demoThreads;if(supabase){const {data,error}=await supabase.from('posts').select('id,title,category,content,created_at,profiles(display_name),comments(count)').order('created_at',{ascending:false});if(!error)rows=data.map(x=>({...x,author:x.profiles?.display_name||'名無しさん',comment_count:x.comments?.[0]?.count||0}));}const q=search.value.toLowerCase();rows=rows.filter(x=>(filter.value==='all'||x.category===filter.value)&&(`${x.title} ${x.content}`).toLowerCase().includes(q));list.innerHTML=rows.length?rows.map(x=>`<a class="thread" href="#/thread/${x.id}"><span class="badge">${escapeHtml(x.category)}</span><h3>${escapeHtml(x.title)}</h3><div class="meta"><span>${escapeHtml(x.author)}</span><span>${formatDate(x.created_at)}</span><span>💬 ${x.comment_count||0}</span></div></a>`).join(''):'<div class="empty">投稿がありません。</div>';};search.oninput=draw;filter.onchange=draw;app.querySelector('#new-thread').onclick=()=>location.hash='/new';await draw();}
async function renderLogin(){const user=await currentUser();if(user){location.hash='/home';return;}app.innerHTML='<section class="form-page"><p class="eyebrow">WELCOME</p><h1>ログイン</h1><p>投稿・コメントをするにはGitHubアカウントでログインしてください。</p><button id="github-login" class="button button-primary">GitHubでログイン</button></section>';app.querySelector('#github-login').onclick=signIn;}
async function renderNew(){const user=await requireAuth();if(!user)return;app.replaceChildren(document.querySelector('#new-template').content.cloneNode(true));app.querySelector('#thread-form').onsubmit=async e=>{e.preventDefault();const form=new FormData(e.currentTarget);const {error}=await supabase.from('posts').insert({author_id:user.id,title:form.get('title'),category:form.get('category'),content:form.get('content')});if(error){alert(error.message);return;}location.hash='/home';};}
async function renderThread(id){app.replaceChildren(document.querySelector('#thread-template').content.cloneNode(true));const target=app.querySelector('#thread-detail');let post=demoThreads.find(x=>x.id===id);let comments=[];if(supabase){const {data}=await supabase.from('posts').select('*,profiles(display_name)').eq('id',id).single();post=data&&{...data,author:data.profiles?.display_name||'名無しさん'};if(data){const r=await supabase.from('comments').select('*,profiles(display_name)').eq('post_id',id).order('created_at');comments=r.data||[];}}if(!post){target.innerHTML='<div class="empty">投稿が見つかりません。</div>';return;}target.innerHTML=`<div class="detail-card"><span class="badge">${escapeHtml(post.category)}</span><h1>${escapeHtml(post.title)}</h1><div class="meta"><span>${escapeHtml(post.author)}</span><span>${formatDate(post.created_at)}</span></div><p class="content">${escapeHtml(post.content)}</p></div><section class="comments"><h2>コメント</h2>${comments.length?comments.map(c=>`<div class="comment"><strong>${escapeHtml(c.profiles?.display_name||'名無しさん')}</strong><div class="meta">${formatDate(c.created_at)}</div><p class="content">${escapeHtml(c.content)}</p></div>`).join(''):'<div class="empty">まだコメントはありません。</div>'}${supabase?'<form id="comment-form" class="comment-form"><textarea name="content" required placeholder="コメントを書く"></textarea><button class="button button-primary">コメントする</button></form>':'<div class="notice">Supabase設定後にコメント機能が有効になります。</div>'}</section>`;const form=target.querySelector('#comment-form');if(form)form.onsubmit=async e=>{e.preventDefault();const user=await requireAuth();if(!user)return;const {error}=await supabase.from('comments').insert({post_id:id,author_id:user.id,content:new FormData(form).get('content')});if(error){alert(error.message);return;}renderThread(id);};}
async function router(){const path=location.hash.slice(1)||'/home';if(path==='/login')return renderLogin();if(path==='/new')return renderNew();if(path.startsWith('/thread/'))return renderThread(path.split('/')[2]);return renderHome();}
async function signIn(){if(!supabase){alert('Supabaseの設定がまだ完了していません。');return;}const {error}=await supabase.auth.signInWithOAuth({provider:'github',options:{redirectTo:location.href.split('#')[0]}});if(error)alert(error.message);}
loginButton.onclick=async()=>{if(!supabase){alert('Supabaseの設定がまだ完了していません。');return;}const user=await currentUser();if(user){await supabase.auth.signOut();location.hash='/home';router();return;}location.hash='/login';};
if(supabase){const {data:{session}}=await supabase.auth.getSession();updateAuthUI(session);supabase.auth.onAuthStateChange((_event,session)=>{updateAuthUI(session);if(session&&location.hash==='#/login')location.hash='/home';});}
window.addEventListener('hashchange',router);router();
